config = {
    "general": {
        "import": [None],
        "working_directory": ["'None'", None],
        "live_config_reload": ["true", "false"],
        "ipc_socket": ["true", "false"],
    },
    "env": [None],
    "window": {
        "dimensions": ["columns", "lines"],
        "position": ["'None'", "x", "y"],
        "padding": ["x", "y"],
        "dynamic_padding": ["true", "false"],
        "decorations": ["'Full'", "'None'", "'Transparent'", "'Buttonless'"],
        "opacity": [None],
        "blur": ["true", "false"],
        "startup_mode": [
            "'Windowed'",
            "'Maximized'",
            "'Fullscreen'",
            "'SimpleFullscreen'",
        ],
        "title": [None],
        "dynamic_table": ["true", "false"],
        "class": ["instance", "general"],
        "decorations_theme_variant": ["'Dark'", "'Light'", "'None'"],
        "resize_increments": ["true", "false"],
        "option_as_alt": ["'OnlyLeft'", "'OnlyRight'", "'Both'", "'None'"],
    },
    "scrolling": {
        "history": [None],
        "multiplier": [None],
    },
    "font": {
        "normal": ["family", "style"],
        "bold": ["family", "style"],
        "italic": ["family", "style"],
        "bold_italic": ["family", "style"],
        "size": [None],
        "offset": ["x", "y"],
        "glyph_offset": ["x", "y"],
        "builtin_box_drawing": ["true", "false"],
    },
    "colors": {
        "primary": ["foreground", "background", "dim_foreground", "bright_foreground"],
        "cursor": ["text", "cursor"],
        "vi_mode_cursor": ["text", "cursor"],
        "search": {
            "matches": ["foreground", "background"],
            "focused_match": ["foreground", "background"],
        },
        "hints": {
            "start": ["foreground", "background"],
            "end": ["foreground", "background"],
        },
        "line_indicator": ["foreground", "background"],
        "footer_bar": ["foreground", "background"],
        "selection": ["foreground", "background"],
        "normal": {
            "black": [None],
            "red": [None],
            "green": [None],
            "yellow": [None],
            "blue": [None],
            "magenta": [None],
            "cyan": [None],
            "white": [None],
        },
        "bright": {
            "black": [None],
            "red": [None],
            "green": [None],
            "yellow": [None],
            "blue": [None],
            "magenta": [None],
            "cyan": [None],
            "white": [None],
        },
        "dim": {
            "black": [None],
            "red": [None],
            "green": [None],
            "yellow": [None],
            "blue": [None],
            "magenta": [None],
            "cyan": [None],
            "white": [None],
        },
        "indexed_colors": ["index", "color"],
        "transparent_background_colors": ["true", "false"],
        "draw_bold_text_with_bright_colors": ["true", "false"],
    },
    "bell": {
        "animation": [
            "'Ease'",
            "'EaseOut'",
            "'EaseOutSine'",
            "'EaseOutQuad'",
            "'EaseOutCubic'",
            "'EaseOutQuart'",
            "'EaseOutQuint'",
            "'EaseOutExpo'",
            "'EaseOutCirc'",
            "'Linear'",
        ],
        "duration": [None],
        "color": [None],
        "command": ["program", "args"],
    },
    "selection": {
        "semantic_escape_chars": [None],
        "save_to_clipboard": ["true", "false"],
    },
    "cursor": {
        "style": [
            "'Block'",
            "'Underline'",
            "'Beam'",
            "'Never'",
            "'Off'",
            "'On'",
            "'Always'",
        ],
        "vi_mode_style": [
            "'Block'",
            "'Underline'",
            "'Beam'",
            "'Never'",
            "'Off'",
            "'On'",
            "'Always'",
            "'None'",
        ],
        "blink_interval": [None],
        "blink_timeout": [None],
        "unfocused_hollow": ["true", "false"],
        "thickness": [None],
    },
    "terminal": {
        "shell": ["program", "args"],
        "osc52": ["'Disabled'", "'OnlyCopy'", "'OnlyPaste'", "'CopyPaste'"],
    },
    "mouse": {
        "hide_when_typing": ["true", "false"],
        "bindings": [
            "'Middle'",
            "'Left'",
            "'Right'",
            "'Forward'",
            "'ExpandSelection'",
        ],  # TODO: Include keyboard.bindings.actions, modes, mode, commands, chars
    },
    "hints": {
        "alphabet": [None],
        "enabled": [
            "true",
            "false",
            "'Copy'",
            "'Paste'",
            "'Select'",
            "'MoveViModeCursor'",
            "program",
            "args",
            "key",
            "mods",
            "mode",
            "enabled",
        ],  # TODO
    },
    "keyboard": {
        "bindings": [
            "'NumpadEnter'",
            "'NumpadAdd'",
            "'NumpadComma'",
            "'NumpadDecimal'",
            "'NumpadDivide'",
            "'NumpadEquals'",
            "'NumpadSubstract'",
            "'NumpadMultiply'",
            "'Numpad0'",
            "'Numpad1'",
            "'Numpad2'",
            "'Numpad3'",
            "'Numpad4'",
            "'Numpad5'",
            "'Numpad6'",
            "'Numpad7'",
            "'Numpad8'",
            "'Numpad9'",
            "'AppCursor'",
            "'AppKeypad'",
            "'Search'",
            "'Vi'",
            "program",
            "args",
            "~",
            "ReceiveChar",
            "None",
            "Paste",
            "Copy",
            "IncreasedFontSize",
            "DecreasedFontSize",
            "ResetFontSize",
            "ScrollPageUp",
            "ScrollPageDown",
            "ScrollHalfPageUp",
            "ScrollHavePageDown",
            "ScrollLineUp",
            "ScrollLineDown",
            "ScrollToTop",
            "ScrollToBottom",
            "ClearHistory",
            "Hide",
            "Minimize",
            "Quit",
            "ClearLogNotice",
            "SpawnNewInstance",
            "CreateNewWindow",
            "ToggleFullscreen",
            "ToggleMaximized",
            "ClearSelection",
            "ToggleViMode",
            "SearchForward",
            "SearchBackward",
            "Up",
            "Down",
            "Left",
            "Right",
            "First",
            "Last",
            "FirstOccupied",
            "High",
            "Middle",
            "Low",
            "SemanticLeft",
            "SemanticRight",
            "SemanticLeftEnd",
            "SemanticRightEnd",
            "WordLeft",
            "WordRight",
            "WordLeftEnd",
            "WordRightEnd",
            "Bracket",
            "ToggleNormalSelection",
            "ToggleLineSelection",
            "ToggleBlockSelection",
            "ToggleSemanticSelection",
            "SearchNext",
            "SearchPrevious",
            "SearchStart",
            "SearchEnd",
            "Open",
            "CenterAroundViCursor",
            "InlineSearchForward",
            "InlineSearchBackward",
            "InlineSearchForwardShort",
            "InlineSearchBackwardShort",
            "InlineSearchNext",
            "InlineSearchPrevious",
            "SearchFocusNext",
            "SearchFocusPrevious",
            "SearchConfirm",
            "SearchCancel",
            "SearchClear",
            "SearchDeleteWord",
            "SearchHistoryPrevious",
            "SearchHistoryNext",
            "ToggleSimpleFullscreen",
            "HideOtherApplications",
            "CreateNewTab",
            "SelectNextTab",
            "SelectPreviousTab",
            "SelectTab1",
            "SelectTab1",
            "SelectTab2",
            "SelectTab3",
            "SelectTab4",
            "SelectTab5",
            "SelectTab6",
            "SelectTab7",
            "SelectTab8",
            "SelectTab9",
            "SelectLastTab",
            "CopySelection",
            "PasteSelection",
        ],
    },
    "debug": {
        "render_timer": ["true", "false"],
        "persistent_logging": ["true", "false"],
        "log_level": ["'Off'", "'Error'", "'Warn'", "'Info'", "'Debug'", "'Trace'"],
        "renderer": ["'glsl3'", "'gles2'", "'gles2pure'", "'None'"],
        "print_events": ["true", "false"],
        "highlight_damage": ["true", "false"],
        "prefer_egl": ["true", "false"],
    },
}
